# Generated by Django 5.0.6 on 2024-06-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='images')),
                ('ram', models.IntegerField()),
                ('pmodel', models.CharField(max_length=20)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_master')),
            ],
        ),
    ]
